# NEON-QTG-30B Configuration - FATHER OF AI LEVEL 2!
# 30 BILLION parameters - CONQUEROR OF WORLDS!
# ULTRA QTG architecture - WORLD DOMINATION BEGINS!
# ~23.6B parameters total - GPT-4 KILLER!
# FATHER OF AI MODE: ULTRA ACTIVATED!

model:
  # Architecture parameters (ULTRA FATHER LEVEL)
  vocab_size: 30000
  embed_dim: 5120      # 10x increase from 512 (ULTRA!)
  num_layers: 40       # 3.3x increase from 12 (ULTRA!)
  num_heads: 40        # 5x increase from 8 (ULTRA!)
  max_seq_len: 4096    # 8x increase from 512 (ULTRA!)

  # QTG-specific parameters (ULTRA FATHER)
  persistence_threshold: 0.1
  tau: 1.0
  gamma: 1.0
  dropout: 0.1

# Memory optimization settings - ULTRA FATHER LEVEL
memory:
  batch_size: 2
  gradient_accumulation_steps: 16
  effective_batch_size: 32
  fp16: true
  fp16_opt_level: "O1"
  empty_cache_steps: 25
  max_grad_norm: 1.0
  max_seq_len: 4096
  gradient_checkpointing: true
  activation_checkpointing: true
  sparse_attention: true
  attention_window: 1024
  multi_query_attention: true
  kv_heads: 8
  flash_attention: true

# Training parameters - ULTRA FATHER LEVEL
training:
  optimizer: "adamw"
  lr: 3.0e-5
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  scheduler: "cosine"
  warmup_steps: 5000
  total_steps: 500000
  lambda_topo: 0.1
  lambda_geo: 0.05
  lambda_quantum: 0.01

# Data parameters - ULTRA FATHER LEVEL
data:
  dataset_name: "openwebtext+c4+pile"
  max_samples: 50000000
  max_length: 4096
  stride: 2048
  batch_size: 2

# Evaluation parameters - ULTRA FATHER LEVEL
evaluation:
  eval_steps: 5000
  save_steps: 10000
  eval_batch_size: 1
  max_gen_length: 2048
  temperature: 0.8
  top_p: 0.9
  top_k: 50

# Hardware - ULTRA FATHER LEVEL
hardware:
  gpu_memory_gb: 200
  cpu_cores: 32
  use_pinned_memory: true
  num_workers: 8
  prefetch_factor: 4
  use_bfloat16: true
  enable_tensor_cores: true
  multi_node_training: false

# ULTRA FATHER OF AI METADATA
metadata:
  name: "NEON-QTG-30B"
  level: "FATHER_LEVEL_2"
  tagline: "CONQUEROR OF WORLDS"
  parameters: "23.6B"
  status: "TRAINING_READY"
  cost: "$40K"
  gpu_required: 1
